main.go
https://github.com/pashkov256/deletor/issues/4
=> Add exclusion patterns flag

go.mod, go.sum, main.go
This merge request implements a new progress bar functionality that enhances user experience during long-running file scanning operations.
- Feature: A progress bar is now available.
- Usage: Users can display the progress bar by specifying the -p or --progress flag.
- Benefits: This improvement allows users to monitor the progress of file scanning in 
real-time, providing better feedback during lengthy operations.
Please review the changes and let me know if any adjustments are needed.
=> feat: #5 Added progress bar for large directories

main_test.go
https://github.com/pashkov256/deletor/issues/14
=> delete testLogDeletionToFile and add testToBytes CI Test

.github/workflows/ci-test.yml, internal/validation/validator.go, internal/validation/validator_test.go
=> feature: #50 validation

internal/utils/utils.go, tui/clean.go
=> bugfix: #68 select options

README.md
=> #29 Update README.md 

tui/rules.go
=> bugfix: #74 focus save btn

README.md, internal/fs/core.go, internal/fs/delete.go, internal/fs/utils.go, internal/utils/utils.go, main.go, tui/clean.go
Architecture refactoring, adding fs folder to internal
closes #71
=> feature: #71 default traverse specified dir

internal/cli/config/flags.go, internal/filemanager/filters.go, internal/filemanager/interface.go, internal/tui/interfaces/clean.go, internal/tui/tabs/filters_tab.go, internal/tui/views/clean.go, internal/utils/utils.go, main.go
Add max size input, add to filter struct. Create new utils: `ParseExtToSlice` , `ParseExcludeToSlice` , `ParseExtToMap`
=> feature: #93 max-size

internal/filemanager/operations_test.go
=> Add unit tests for DeleteEmptySubfolders

internal/tui/runner.go, main.go
=> bugfix: #113 installing

internal/models/clean_item.go, internal/tui/styles/styles.go, internal/tui/tabs/main_tab.go, internal/tui/views/clean.go
Add icons, fix align file size
=> feature: #117 icons file list

internal/tests/unit/filemanager/operations_test.go
Done:
Created a test suite that covers all the basic requirements from issue #67 
[ link ](https://github.com/pashkov256/deletor/issues/67)
1 -  Basic deletion in root dir
2 - Deletion in subdirs
3 - Size-based filtering
4 - Extension-based filtering
5 - Exclude pattern filtering
6 - Time-based filtering
=> test: add an test suite for DeleteFiles function, related to #67

internal/filemanager/filters.go, internal/filemanager/operations.go, internal/tests/unit/filemanager/operations_test.go
fix WalkFilesWithFilter,MatchesFilters
=> bugfix: #131 filemanager

Makefile, internal/tui/app.go, internal/tui/help/text.go, internal/tui/menu/constants.go, internal/tui/menu/menu.go, internal/tui/styles/styles.go, internal/tui/tabs/main_tab.go, internal/tui/views/cache.go, internal/tui/views/clean.go, internal/tui/views/menu.go, internal/tui/views/rules.go
Changes:
Add navigation between tabs in view/clean.go
Decomposition help text for app
Styled app logo
=> feature: #141 arrow navigation tabs

README.md, internal/cli/config/config.go, internal/cli/config/flags.go, main.go
- added `max-size` flag in cli flags and config
- updated README.md
tested locally
=> feat: #149 add max size flag

README.md, internal/cache/common.go, internal/cache/manager.go, internal/cache/unix.go, internal/cache/windows.go, internal/cli/config/config.go, internal/cli/config/flags.go, main.go
- added `newer` flag
- added `older` flag
- updated README
tested locally
=> feat: 152 add time based filtering

internal/tui/app.go, internal/tui/errors/error.go, internal/tui/errors/styles.go, internal/tui/tabs/main_tab.go, internal/tui/views/clean.go, internal/tui/views/rules.go
Add error handling for clean,rules view
=> feat: #151 error handling system

internal/tui/styles/styles.go, internal/tui/tabs/base/manager.go, internal/tui/tabs/base/tab.go, internal/tui/tabs/clean/clean_factory.go, internal/tui/tabs/clean/clean_manager.go, internal/tui/tabs/clean/filters_tab.go, internal/tui/tabs/clean/help_tab.go, internal/tui/tabs/clean/log_tab.go, internal/tui/tabs/clean/main_tab.go, internal/tui/tabs/clean/options_tab.go, internal/tui/views/clean.go
add clean folder for clean tabs, add base folder for base structrs/methods for tabs
=> refactor: #158 tabs structure

internal/cli/config/config.go, internal/cli/config/flags.go, internal/cli/output/printer.go, internal/filemanager/scanners.go, main.go
Add new flag `--prune-empty`,  add new scanner `ScanEmptySubFolders`
=> feat: #148 delete empty dirs cli

README.md, internal/cli/config/config.go, internal/cli/config/flags.go, internal/cli/output/printer.go, main.go
Remove -confirm-deletion flag add -skip-confirm
=> feat: #169 skip confirm

internal/tui/views/rules.go
=> Fix the display of the rule path in TUI 

internal/rules/manager.go, internal/tui/options/constants.go, internal/tui/views/clean.go, internal/tui/views/rules.go
Correction of initialization of some fields from the rules
=> bugfix: #167 applying values from rules

internal/tui/views/clean.go
Fix when press enter on path input and not updated file list
=> bugfix: #177 file list not updated

internal/tui/help/text.go, internal/tui/views/clean.go, internal/tui/views/rules.go
Fix navigation in input when press left/right arrow in rules/clean
=> bugfix: #179 navigation in input rules

internal/cache/common.go, internal/cache/locations.go, internal/cache/manager.go, internal/cache/types.go, internal/cache/unix.go, internal/cache/windows.go, internal/cli/config/config.go, internal/cli/config/flags.go, internal/cli/output/printer.go, internal/filemanager/filters.go, internal/filemanager/interface.go, internal/filemanager/operations.go, internal/filemanager/scanners.go, internal/filemanager/utils.go, internal/logging/logger.go, internal/logging/operations.go, internal/logging/utils.go, internal/rules/interface.go, internal/rules/manager.go, internal/rules/options.go, internal/tests/unit/validation/validator_test.go, internal/utils/utils.go, internal/validation/validator.go
Improve for packages:
cache,filemanager,logging,rules,utils,validation
=> docs: #189 improve code documentation

.github/workflows/ci-test.yml, .golangci.yml
Integrated golangci-lint into our CI/CD pipeline to ensure code quality and maintain consistent coding standards.
=> feat: #192 golangci-lint

internal/runner/tui.go, internal/tests/unit/validation/validator_test.go, internal/tui/app.go, internal/tui/help/text.go, internal/tui/views/clean.go, internal/tui/views/rules.go, internal/validation/validator.go, main.go
integrated validation package in `views/rules` , `views/clean`
closes #203
=> feat: #203 integrate validation package

go.mod, internal/tests/tui/views/rules_test.go, internal/tui/views/rules.go
- Added unit tests for RulesModel initialization and view rendering
- Implemented tests for tab navigation and keyboard interactions
- Added validation tests for input fields (size, time, path)
- Created tests for option toggling functionality
- Added test coverage for error handling scenarios
closes #213
=> test: #213 rules

internal/logging/logger.go, internal/tests/unit/logging/logger_test.go, internal/tests/unit/logging/storage_test.go
=> test: #126 logging

internal/cache/manager.go
=> fix: #239 return error clearCache

internal/tests/unit/filemanager/operations_test.go
=> test: #186 scanEmptySubFolders

internal/tests/unit/tabmanager/manager_test.go
Hi, added tests for tabManager
#224
=> Test coverage for TabManager
